### ISSUE TITLE
Load PDB files, mol2 files and sdf files from an external URL

### ISSUE THREAD

**Issue by JerryJohnsonLee** [luna215/molstar#3]
We will prepare protein and ligand structures in the format of pdb, mol2 or sdf and the structures will be stored on an Amazon S3 bucket. We would like the Molstart window starting blank. There are two buttons outside of the Molstar window. One for loading the protein structure and the other for loading ligand structure.

We will add URL to example files shortly.

**Comment by luna215** [comment]
https://molstar.org/demos/lighting/

**Comment by JerryJohnsonLee** [comment]
Here is the pdb file: https://molstar-example.s3.us-west-1.amazonaws.com/2ym3_protein_processed.pdb
and the ligand file: https://molstar-example.s3.us-west-1.amazonaws.com/2ym3_ligand.mol2

**Comment by luna215** [comment]
@JerryJohnsonLee Here are two videos of molstar being able to read both PDB and mol2 files from s3 buckets:

https://user-images.githubusercontent.com/7971405/185030948-f3c398f9-4c55-4eea-8db0-cce7fddabaa3.mov
https://user-images.githubusercontent.com/7971405/185030937-e981d16c-9539-4feb-8d6d-33c806a4c28a.mov

Let me know if you have trouble downloading these files. If you do, I can upload them to google drive instead.

**Comment by JerryJohnsonLee** [comment]
> @JerryJohnsonLee Here are two videos of molstar being able to read both PDB and mol2 files from s3 buckets:
> 
> https://user-images.githubusercontent.com/7971405/185030948-f3c398f9-4c55-4eea-8db0-cce7fddabaa3.mov https://user-images.githubusercontent.com/7971405/185030937-e981d16c-9539-4feb-8d6d-33c806a4c28a.mov
> 
> Let me know if you have trouble downloading these files. If you do, I can upload them to google drive instead.

Thanks for sharing your progress! Just wanted to make sure you will continue working on implementing the loading through APIs instead of using the side bar.

**Comment by luna215** [comment]
@JerryJohnsonLee If we need to access a file via an API, we should still be able to do that. Implementing/plugging in the code should not be difficult. I didn't think it was necessary to grab these files via an API. However, if we're dealing with sensitive data that lives in s3, then an API would be a way better approach. In this case, then we'll need to setup an API endpoint that grabs the appropriate files from the appropriate s3 bucket. Since we don't want to expose this information publicly then we'll need to create `environment` variables wherever we run the api (in Heroku in thise case).

I think it's best to implement for features we need as opposed to features we think we _might_ need in the future. There has just been too many occasions in companies I worked in where I built something in the hope that we'll need it someday and never end up using it. I think it's a waste of time and resources.

**Comment by JerryJohnsonLee** [comment]
At this current stage we are creating a demo version of our product so the pdb files and ligand files will be prepared in advance, but they are still stored in s3 (despite being public) and be loaded into the page without manually loading it through the side bar. (In fact in our product the structures will be loaded to the Mol* window once the webpage loads, but the structures will also change after we run some algorithm. So we want you to create a button that loads the structure, and we will know how we can load new structures generated by our algorithm as soon as the files are created.) In the future since we are creating a platform for multiple users to use, the data will become sensitive and we will rely on more complicated APIs to load the data.

**Comment by luna215** [comment]
@JerryJohnsonLee No worries. I think I got confused because you mentioned API, and that usually lives in the backend of systems. If I am understanding you correctly, we want to reuse some of the functionality from within mol* to grab the two files that you shared in the description?

So, for the sake of this demo, you just want 2 buttons that read `Protein Structure` and `Ligand Structure`
![Screen Shot 2022-08-17 at 6 12 24 PM](https://user-images.githubusercontent.com/7971405/185270411-f65e1bcf-03ad-4bc2-b980-59fd740879a2.png)

I was under the impression that users would want to provide a url to grab the structures from various sources and not be limited to s3. 

> structures will also change after we run some algorithm.
Based on this, before we load the structure onto the viewer, algorithms will be ran? If this is correct, then we can definitely do this. While we're reading the file, we can plugin the custom algorithm to change the structure before displaying it on the viewer

> we will know how we can load new structures generated by our algorithm as soon as the new structures are available.
I'm confused by this. Does this mean that for new structures that our available - lets say in s3 for now - then we'll create more buttons to display each new individual structure? Or when you say new structures, you're referring to different format files?

**Comment by luna215** [comment]
@JerryJohnsonLee Check out the latest viewer. Made it identical to the sample you shared with me. I also show case that we're downloading the file from a press of a button:

https://drive.google.com/file/d/1sWUBV5AYwCXnsu-tY-HYqJdiEIhB3El9/view?usp=sharing

**Comment by JerryJohnsonLee** [comment]
@luna215  Nice progress! When you load the ligand structure can you still retain the loaded protein?

> Based on this, before we load the structure onto the viewer, algorithms will be ran? If this is correct, then we can definitely do this. While we're reading the file, we can plugin the custom algorithm to change the structure before displaying it on the viewer

When we load the page there will be some initial structures to be loaded, and at the same time the algorithm starts to run (it takes some time to finish). Once it finishes there will be a bunch of new ligand structures generated, and we want to show them as interactable components on the webpage. Once the user clicks one of them, the Mol* window will load the new ligand structure.

> I'm confused by this. Does this mean that for new structures that our available - lets say in s3 for now - then we'll create more buttons to display each new individual structure? Or when you say new structures, you're referring to different format files?
Yes when the new structures are available, there will be a region on the webpage that shows the 2D structures of all new ligands. These can be buttons or any other webpage element that is interactable. These are all in .mol2/.sdf/.pdb format, but they are different structures.

In the next meeting we will explain to you what our final product looks like, and we hope you can understand how these issues connect to our real requirements by then.

**Comment by luna215** [comment]
Migrated to organization molstar repo
